name: Build and Deploy

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t website .

      - name: Stop and Remove existing container
        run: |
          docker stop website || true
          docker rm website || true

      - name: Run Docker container
        run: docker run -d -p 8000:80 --name website website
